# Generated by Django 3.1 on 2020-10-27 21:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movie_app', '0003_movie'),
    ]

    operations = [
        migrations.AddField(
            model_name='director',
            name='actors',
            field=models.ManyToManyField(through='movie_app.Movie', to='movie_app.Actor'),
        ),
    ]
